import { Download, FileVideo, LinkIcon, Sparkles } from "lucide-react";
import Link from "next/link";

export type EnhancedRecord = {
  id: string;
  fileName: string;
  createdAt: string;
  duration: string;
  status: "Completed" | "Processing" | "Queued";
  frameRate: string;
  exportFormat: "mp4" | "mov" | "mkv";
  features: string[];
};

type Props = {
  items: EnhancedRecord[];
};

export function HistoryList({ items }: Props) {
  return (
    <section className="rounded-3xl border border-white/5 bg-black/30 p-6 text-white shadow-lg shadow-black/20">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h2 className="text-lg font-semibold tracking-tight">
            Enhancement History
          </h2>
          <p className="mt-1 text-sm text-white/60">
            Audit-ready timeline of every UHD master generated by VisionForge.
          </p>
        </div>
        <Link
          href="#"
          className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-semibold uppercase tracking-wide text-white/60 transition hover:border-emerald-300/50 hover:text-white"
        >
          <LinkIcon className="h-3.5 w-3.5" />
          View cloud library
        </Link>
      </div>

      <div className="mt-6 space-y-4">
        {items.map((entry) => (
          <article
            key={entry.id}
            className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-white/[0.04] p-4 text-sm"
          >
            <div className="flex items-center gap-3">
              <span className="flex h-12 w-12 items-center justify-center rounded-xl border border-white/10 bg-black/30">
                <FileVideo className="h-5 w-5 text-emerald-300" />
              </span>
              <div>
                <p className="font-semibold text-white">{entry.fileName}</p>
                <div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-white/50">
                  <span>{entry.duration}</span>
                  <span>•</span>
                  <span>{entry.frameRate}</span>
                  <span>•</span>
                  <span>{entry.exportFormat.toUpperCase()}</span>
                </div>
                <div className="mt-2 flex flex-wrap gap-2">
                  {entry.features.map((feature) => (
                    <span
                      key={feature}
                      className="flex items-center gap-1 rounded-full border border-white/10 bg-black/40 px-3 py-1 text-[10px] font-semibold uppercase tracking-wide text-white/50"
                    >
                      <Sparkles className="h-3 w-3 text-emerald-300" />
                      {feature}
                    </span>
                  ))}
                </div>
              </div>
            </div>
            <div className="flex flex-col items-end gap-3 text-xs text-white/50">
              <span>{entry.status}</span>
              <span>{entry.createdAt}</span>
              <button className="flex items-center gap-2 rounded-xl border border-white/10 bg-emerald-500/10 px-4 py-2 font-semibold uppercase tracking-wider text-emerald-200 transition hover:border-emerald-400/50 hover:text-white">
                <Download className="h-4 w-4" />
                Export
              </button>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
